### ISSUE TITLE
v3.0.0开发

### ISSUE THREAD

**Issue by genaller** [genaller/genal-chat#20]

**Comment by PerfectYan** [comment]
你这是vue2版本啊，不是vue3

**Comment by PerfectYan** [comment]
趁现在还早，改成vue3的，市面上第一篇vue3+ts+nest教程

**Comment by genaller** [comment]
@PerfectYan 不是呀朋友 v3.0就是这是第三版本开发的分支

**Comment by genaller** [comment]
@PerfectYan  哈哈哈 等3.0成熟了肯定会重构的 目前还要继续迭代功能
