### ISSUE TITLE
不兼容IE11

### ISSUE THREAD

**Issue by ZhongJinMing** [genaller/genal-chat#33]
hi，作者你好，我在运行这个项目的时候发现不兼容IE11浏览器，主要是以下原因导致的：
1. viewer和object-assign这两个依赖在编译后依然会有箭头函数和let关键字，而这两个特性在IE11上不支持

我按vuecli4官网提供的方法改过配置，包含修改matin.ts时的包引入和babel.config.js的相关配置，但编译后的包依然包含上述两个新特性

这个有解决办法吗

**Comment by genaller** [comment]
目前需求不在兼容ie11, 我以后看看
