### ISSUE TITLE
建议接入语音播放消息

### ISSUE THREAD

**Issue by Yakumo-Yukari** [genaller/genal-chat#43]
可以让用户选择是否开启语音播放聊天消息  这样就不用一直盯着聊天室 可以一边做其他事一边听聊天室的消息

**Comment by genaller** [comment]
有意思 我先调研调研

**Comment by Yakumo-Yukari** [comment]
> 有意思 我先调研调研

大佬现在用户的昵称修改是无限制次数的吗？昵称修改感觉可以限定在一定次数内比较好

**Comment by genaller** [comment]
用戶信息的修改沒有限制次數哦 限制次数意义不大 次数完了就换个账号我也限制不了了

**Comment by genaller** [comment]
> > 有意思 我先调研调研
> 
> 大佬现在用户的昵称修改是无限制次数的吗？昵称修改感觉可以限定在一定次数内比较好

用戶信息的修改沒有限制次數哦 限制次数意义不大 次数完了就换个账号我也限制不了了
