### ISSUE TITLE
没有找到后端的sql文件

### ISSUE THREAD

**Issue by jiaqiyu543** [genaller/genal-chat#44]
Unable to connect to the database. Retrying (1)... +35ms
Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

**Comment by genaller** [comment]
这个问题是mysql版本不兼容导致的 可以参考这篇文章https://blog.csdn.net/qq_41831345/article/details/83150502

**Comment by genaller** [comment]
> Unable to connect to the database. Retrying (1)... +35ms
> Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

这个问题是mysql版本不兼容导致的 可以参考这篇文章https://blog.csdn.net/qq_41831345/article/details/83150502

**Comment by jiaqiyu543** [comment]
抱歉，初步接触，感谢🙏回答，我再研究一下，请问后端不需要配置表的吗？   我好像没找到sql文件

**Comment by genaller** [comment]
> 抱歉，初步接触，感谢🙏回答，我再研究一下，请问后端不需要配置表的吗？ 我好像没找到sql文件

不需要的哦 我用的typeorm 也就是你只需要能运行 typeorm会按照我写的xxx.entity.ts的模型建立好对应的表的 你运行起来了吗

**Comment by jiaqiyu543** [comment]
还没有   在忙别的事    非常感谢您的回答   到时候不行  再请教您
