### ISSUE TITLE
考虑做个docker安装版么

### ISSUE THREAD

**Issue by pangjian** [genaller/genal-chat#45]
跟MySQL环境不匹配的问题调了半天, 考虑做个docker版的吗, 可以快速搭建出来

**Comment by genaller** [comment]
> 跟MySQL环境不匹配的问题调了半天, 考虑做个docker版的吗, 可以快速搭建出来

mysql的问题我特意留了文章呀 没有解决问题吗 docker的话我其实不是很熟悉 以后用上了肯定会更新的

**Comment by pangjian** [comment]
> > 跟MySQL环境不匹配的问题调了半天, 考虑做个docker版的吗, 可以快速搭建出来
> 
> mysql的问题我特意留了文章呀 没有解决问题吗 docker的话我其实不是很熟悉 以后用上了肯定会更新的

编码的问题也搞了一段时间, utf8mb4编码需要专门配置才行.

**Comment by genaller** [comment]
> > > 跟MySQL环境不匹配的问题调了半天, 考虑做个docker版的吗, 可以快速搭建出来
> > 
> > 
> > mysql的问题我特意留了文章呀 没有解决问题吗 docker的话我其实不是很熟悉 以后用上了肯定会更新的
> 
> 编码的问题也搞了一段时间, utf8mb4编码需要专门配置才行.

这个代码里面配置了应该不需要操作mysql才对， 很奇怪

**Comment by lcxw** [comment]
> 跟MySQL环境不匹配的问题调了半天, 考虑做个docker版的吗, 可以快速搭建出来

https://github.com/lcxw/genal-chat

**Comment by BoBoooooo** [comment]
> > > 跟MySQL环境不匹配的问题调了半天, 考虑做个docker版的吗, 可以快速搭建出来
> > 
> > 
> > mysql的问题我特意留了文章呀 没有解决问题吗 docker的话我其实不是很熟悉 以后用上了肯定会更新的
> 
> 编码的问题也搞了一段时间, utf8mb4编码需要专门配置才行.

编码问题新建数据库的时候注意选择 
![image](https://user-images.githubusercontent.com/25972237/99926576-2a5f9080-2d7d-11eb-9780-b9ec6625339b.png)

然后启动项目会自动生成表结构的,如果是MACOS系统连不上数据库的情况参照大佬给出的那篇文章设置下alias就没问题了
