### ISSUE TITLE
图能换一下不，一进去，，，手都差点给我吓掉了

### ISSUE THREAD

**Issue by Alarikshaw** [genaller/genal-chat#60]

**Comment by hahazai223** [comment]
> _No description provided._

时不时有网友捣乱，实际上在我掌控内的，现在已经清除了

**Comment by Alarikshaw** [comment]
真的吗，我不信(听起来你底气不足哟)，哈哈，刚刚我看到那个图，真的手忙脚乱的关掉，，，，

**Comment by Alarikshaw** [comment]
有撤回功能吗，，，，，

**Comment by hahazai223** [comment]
> 有撤回功能吗，，，，，

做了角色权限 我是管理员哈哈哈一键清空他们，撤回没做

**Comment by Alarikshaw** [comment]
666 很强，可否告知下数据库的排序规则是哪一种？
