### ISSUE TITLE
请问如何修改mysql连接地址  

### ISSUE THREAD

**Issue by Yakumo-Yukari** [genaller/genal-chat#70]
比如mysql是部署在另外的服务器上不是在同一台服务器上 要怎么修改mysql的链接地址

**Comment by genaller** [comment]
只能是电脑上改好传到linux服务器，或者你直接在服务器vim改了

**Comment by genaller** [comment]
const connection = await createConnection({
  type: 'mysql',
  host: 'localhost',
  port: 3306,
  username: 'test',
  password: 'test',
  database: 'test',
});
似乎host和port字段改一下估计可以

**Comment by Yakumo-Yukari** [comment]
> const connection = await createConnection({
> type: 'mysql',
> host: 'localhost',
> port: 3306,
> username: 'test',
> password: 'test',
> database: 'test',
> });
> 似乎host和port字段改一下估计可以




好的谢谢了！
