### ISSUE TITLE
有详细的安装教程吗

### ISSUE THREAD

**Issue by kaliisra** [genaller/genal-chat#73]
有详细的安装教程吗，我的打包 老是报错，nodejs版本也一样

**Comment by genaller** [comment]
> 有详细的安装教程吗，我的打包 老是报错，nodejs版本也一样

https://github.com/genaller/genal-chat/blob/master/%E9%98%BF%E7%AB%A5%E6%9C%A8%E8%81%8A%E5%A4%A9%E5%AE%A4%E9%83%A8%E7%BD%B2%E8%AF%B4%E6%98%8E.md
这个文档没有解决问题吗

**Comment by genaller** [comment]
可能你需要升级一下node吧
