### ISSUE TITLE
无法创建群

### ISSUE THREAD

**Issue by ghost** [genaller/genal-chat#84]
rt 创建群之后，提交没有反应。
另外如何让创建的群默认显示在所有注册用户的列表上？

**Comment by genaller** [comment]
> rt 创建群之后，提交没有反应。
> 另外如何让创建的群默认显示在所有注册用户的列表上？

创建成功你就自动进入该群了，图片没看见？，其他人进群是需要搜索进入的

**Comment by sanboukarasu** [comment]
是我搭建的环境的问题。大佬能出个宝塔/aapanel的配置教程吗？

**Comment by genaller** [comment]
> 是我搭建的环境的问题。大佬能出个宝塔/aapanel的配置教程吗？

没用过宝塔呀 感觉是你socket没连上服务器导致的，前端能看见说明就没问题了，后端的话你主要排查一下

**Comment by genaller** [comment]
解决了吗？ 没遇到过这样的问题，是node服务部署出了问题，或者是nginx没配好？

**Comment by xiaorui16888** [comment]
> 解决了吗？ 没遇到过这样的问题，是node服务部署出了问题，或者是nginx没配好？

谢谢作者的关注。是node服务部署出了问题，npm run pm2后，一次启动了多个服务端的进程。然后使用
`pm2 delete 进程id号`，保留一个。然后解决的。
