### ISSUE TITLE
npm build之没有生成dist目录

### ISSUE THREAD

**Issue by xuyichenmo** [genaller/genal-chat#92]
运行完npm run build之后
![image](https://user-images.githubusercontent.com/20925537/128623048-7703e407-db9d-4e59-851c-d593d250cd7c.png)

运行环境Vultr虚拟机Alma Linux
尝试找了一下当前目录，以及Ngin的安装目录，都没有找到

**Comment by genaller** [comment]
genal-chat-client就是一个vue项目，到这个项目终端下面npm run build 然后dist文件就会出现在genal-chat-client下面的，需要你手动移到nginx的html目录下面

**Comment by genaller** [comment]
我估计是你的前端构建需要一定内存，然后你的机子卡死了，你可以现在你的window构建完前端然后在传输到你的远程服务器的nginx里面

**Comment by Fs2qFtoS** [comment]
已经解决啦，谢谢
