### ISSUE TITLE
Invalid value for username

### ISSUE THREAD

**Issue by xuyichenmo** [genaller/genal-chat#93]
运行server端的时候报错：
![image](https://user-images.githubusercontent.com/20925537/128666025-f738f44b-7922-4745-824b-66ec5f8f76c6.png)
app中采用的的配置
![image](https://user-images.githubusercontent.com/20925537/128666075-26d4cc32-bae8-4449-80c0-35cce3c9bbd2.png)
Mysql的密码为123456，默认账户root

**Comment by genaller** [comment]
排查一下是不是你的mysql没有叫做chat的数据库，如果没有，你手动创建一个
